### PR TITLE
Update the install

### PR DESCRIPTION
**Pull request by 0x07CB**
better ?

### CODE REVIEW

**Comment by langonginc** [comment]
That's great. Do you have any question about these new commits?

**Review by langonginc — APPROVED** [review]
I'll progress this tomorrow.

**Comment by 0x07CB** [comment]
> That's great. Do you have any question about these new commits?

Today I have no time. Tomorrow.

**Comment by langonginc** [comment]
@0x07CB That’s okay.

**Comment by 0x07CB** [comment]
> @0x07CB That’s okay.

busy on cybersecurity work I comming back soon.

TTYL,
Rick Sanchez.

**Comment by langonginc** [comment]
Thank you very much.

**Comment by 0x07CB** [comment]
> Thank you very much.

Have a nice day, I coming back soon with the smile to work again on this project. ;)
No problem.

TTYL,
- Rick Sanchez

**Pull request merged**
